### ISSUE TITLE
SOLID Descriptions with Code Samples 

### ISSUE THREAD

**Issue by severus-sn4pe** [severus-sn4pe/mse-softweng-solid#1]
Hi @ThunderKey @mcalzaferri  @nikolaistraessle  @4RealDev

I have create a first draft version of OCP and LSP in 
https://github.com/severus-sn4pe/mse-softweng-solid/wiki

added some examples, but we can also change them if you have better ideas.

We can discuss them here or on teams.

**Comment by ThunderKey** [comment]
@mcalzaferri @nikolaistraessle @4realDev @severus-sn4pe I've created a basic draft of the [SRP page](../wiki/1---SRP).

You can have a look and make changes if you want.

**Comment by ThunderKey** [comment]
@mcalzaferri @nikolaistraessle @4realDev @severus-sn4pe

Since I haven't heard anything about the Wiki page I've created the PDF.
[Ass04_SOL_Principles.pdf](https://github.com/severus-sn4pe/mse-softweng-solid/files/5390973/Ass04_SOL_Principles.pdf)

Any thoughts? If I don't hear anything until tomorrow noon I'll send this to Mr. Kropp

**Comment by nikolaigut** [comment]
The text is ok for me. Thank you

**Comment by mcalzaferri** [comment]
I changed the ocp part to match the code of the project. Rest is ok for me.

**Comment by severus-sn4pe** [comment]
looks good to me, thanks

**Comment by ThunderKey** [comment]
I've sent the mail
